spring:
  application:
    name: wavi

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: http://localhost:8080/api/v1/user/login/oauth2/code/google
            scope:
              - email
              - profile

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

api:
  fastapi:
    base-url: ${FASTAPI_BASE_URL:http://localhost:8080}